language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hawy-dev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hawy-dev/docker-react npm run test
